### YamlMime:YamlDocument
documentType: LandingData
title: Ansible na Documentação do Azure
metadata:
  title: Ansible na Documentação do Azure - Tutoriais, amostras, referência e recursos
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 07/05/2018
  ms.author: tarcher
  ms.openlocfilehash: 3d885c6374530884e761ecbee837d6406dd3e894
  ms.sourcegitcommit: ab3b2482704758ed13cccafcf24345e833ceaff3
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 07/06/2018
  ms.locfileid: "37868610"
abstract:
  description: Utilize o <a href="http://www.ansible.com">Ansible</a> para automatizar o aprovisionamento para a cloud, gestão de configuração e implementações de aplicações.
sections:
- title: Inícios rápidos de cinco minutos
  items:
  - type: paragraph
    text: Configurar o Ansible e utilizá-lo para criar uma VM do Linux no Azure.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Configurar o Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Criar uma VM do Linux
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Tutoriais Passo-a-Passo
  items:
  - type: paragraph
    text: Saiba como utilizar o Ansible para criar e gerir a computação do Azure e infraestrutura de redes.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Crie uma máquina virtual do Linux, incluindo rede virtual, endereço IP público e cartão de interface de rede virtual.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Ligar a uma máquina virtual do Azure e executar um manual de comunicação do Ansible no Cloud Shell.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Criar e gerir um inventário dinâmicas dos seus recursos do Azure.</a>
- title: Referência
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Funções do manual de comunicação
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Versões e funcionalidades
      html: <p><a href="./ansible-matrix.md">Matriz de funcionalidades de módulos e funções</a></p>
    - title: Ferramentas
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Extensão do Visual Studio Code para Ansible</a></p>
